# https://travis-ci.org/HearthSim/hsdecktracker.net
language: ruby
rvm: "2.4.1"

cache: bundler

dist: trusty

before_install:
  - jdk_switcher use oraclejdk8

script: bundle exec jekyll build

after_success: '[[ $TRAVIS_PULL_REQUEST = "false" && $TRAVIS_BRANCH == "master" ]] &&
  bundle exec s3_website install &&
  java -cp $(bundle show s3_website)/*.jar s3.website.Push &&
  curl -X DELETE https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/purge_cache
  -H "Content-Type:application/json" -H "Authorization: Bearer $CF_API_TOKEN"
  --data ''{"purge_everything":true}'''

notifications:
  email:
    on_failure: always
    on_success: change

  irc:
    channels:
      - "chat.freenode.net#hearthsim-commits"
    use_notice: true
    skip_join: true
    on_failure: always
    on_success: change
    template:
      - "(%{branch} @ %{commit} : %{author}): %{message} %{build_url}"
